config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'pages/news', to: 'pages#news', as: :news 
  get 'pages/shows', to: 'pages#shows', as: :shows
  get 'pages/authors', to: 'pages#authors', as: :authors
  get 'pages/popular', to: 'pages#popular', as: :popular
  get 'pages/account', to: 'pages#account', as: :account
  root 'pages#index'

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
  
    def news
    end
  
    def shows
    end
  
    def authors
    end
  
    def popular
    end
  
    def account
    end
  end
  
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Текстовые Сериалы</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header class="header">
    <div class="container">
      <nav class="nav">
        <ul class="nav-list">
          <li class="nav-item"><%= link_to "Главная", root_path, class: "nav-link #{current_page?(root_path) ? 'active' : ''}" %></li>
          <li class="nav-item"><%= link_to "Лента", news_path, class: "nav-link #{current_page?(news_path) ? 'active' : ''}" %></li>
          <li class="nav-item"><%= link_to "Сериалы", shows_path, class: "nav-link #{current_page?(shows_path) ? 'active' : ''}" %></li>
          <li class="nav-item"><%= link_to "Авторы", authors_path, class: "nav-link #{current_page?(authors_path) ? 'active' : ''}" %></li>
          <li class="nav-item"><%= link_to "Популярное", popular_path, class: "nav-link #{current_page?(popular_path) ? 'active' : ''}" %></li>
          <li class="nav-item"><%= link_to "Личный кабинет", account_path, class: "nav-link #{current_page?(account_path) ? 'active' : ''}" %></li>
        </ul>
      </nav>
    </div>
  </header>
  <main class="main">
    <div class="container">
      <%= yield %>
    </div>
  </main>
  <footer class="footer">
    <div class="container">
      <p> NaPiSaNo PROD &copy; 24</p>
    </div>
  </footer>
</body>
</html>

app/views/pages/account.html.erb
<h1>Личный кабинет</h1>
<p>Здесь будет контент личного кабинета.</p>

app/views/pages/authors.html.erb
<h1>Страница авторов</h1>
<p>Страницы авторов. должны быть. тут</p>

app/views/pages/index.html.erb
<h1>Медиа сервис для создания
и чтения текстовых сериалов</h1>
<%= image_tag ("tarantino.jpg") %>
<p>Ну тут короче главная заглавная такая.</p>

app/views/pages/news.html.erb
<h1>Лента новостей</h1>
<p>лента новостей сериалы про пидиди и криминальную америку.</p>

app/views/pages/popular.html.erb
<h1>Страница популярного</h1>
<p>Кто эти люди? ЭТО ЙУХ НА БЛЮДЕ А НЕ ЛЮДИ!!!!.</p>

app/views/pages/shows.html.erb
<h1>Страница сериалов</h1>
<p>Сериалы. интриги. расследования.</p>